name: CD - Deploy to ECS

on:
  workflow_run:
    workflows: ["CI - Build, Scan & Push"]
    types: [completed]
    branches: [main]

env:
  AWS_REGION: eu-west-2

permissions: 
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy image to ECS
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.TF_OPS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: update_task_definition
      
      - name: confirm infrastructure exists
        run: |
          STATUS=$(aws ecs describe-clusters --clusters your-cluster-name --query "clusters[0].status" --output text)
          if [ "$STATUS" != "ACTIVE" ]; then
          echo "Cluster not active"
          exit 0
          else
          echo "Cluster active, proceed to update task definition"
          fi
