name: CD - Deploy to ECS

on:
  workflow_run:
    workflows: ["CI - Build, Scan & Push"]
    types: [completed]
    branches: [main]

env:
  AWS_REGION: eu-west-2
  CLUSTER_NAME: IT-Tools-Cluster
  CONTAINER: IT-Tools-Container
  TASK_DEF: IT-Tools-TD
  IMAGE_TAG: ${{ github.sha }}


permissions: 
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy image to ECS 
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.TF_OPS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: update_task_definition
         
      - name: Fetch Task definition
        id: fetch_td
        run: |
          aws ecs describe-task-definition \
          --task-definition ${{ env.TASK_DEF }} \
          --query taskDefinition > task-definition.json

      - name: Render Amazon ECS task definition
        # if: steps.fetch_td.outcome == 'success'
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
         task-definition: task-definition.json
         container-name: ${{ env.CONTAINER }}
         image: ${{ secrets.IMAGE_URI_PREFIX }}:prod-${{ env.IMAGE_TAG }}

