name: Terraform Destroy Pipeline

permissions: 
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPO: it-tools-repo
  CLUSTER: IT-Tools-Cluster
  CONTAINER: IT-Tools-Container
  SERVICE: IT-Tools_cluster_service

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'Confirm Terraform Destroy' to trigger workflow"
        required: true
        type: string

jobs:
  cancel:
    if: ${{ github.event.inputs.confirm != 'Confirm Terraform Destroy' }}
    name: cancel workflow
    runs-on: ubuntu-latest
    
    steps:
      - name: Terraform destroy not triggered
        run: echo "##Confirmation phrase did not match.
          Terraform destroy was not triggered. 
          Re-run and enter the exact phrase to proceed." >> $GITHUB_STEP_SUMMARY

  destroy:
    if: ${{ github.event.inputs.confirm == 'Confirm Terraform Destroy' }}
    name: destroy app infrastructure
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: infra
  
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.TF_OPS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: terraform_destroy
      
      - name: pull current task definition image tag
        run: |
          echo "image_tag=$(aws ecs describe-task-definition \
          --task-definition $(aws ecs describe-services \
          --cluster ${{ env.CLUSTER }} --services ${{ env.SERVICE }} \
          --query 'services[0].taskDefinition' --output text) \
          --query 'taskDefinition.containerDefinitions[0].image' \
          --output json | jq -r 'split(":") | last')" >> "$GITHUB_OUTPUT"
      
      - name: print latest image tag
        run: echo "${{ steps.latest_image.outputs.image_tag }}" 
    



