name: Build terraform infrastructure

on:
  push:
    branches:
      - main
    paths:
      - infra/**
      - .tfsec/**

permissions: 
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  build:
    name: build infrastructure and security scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: terraform security scan
        uses: triat/terraform-security-scan@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.TF_OPS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: terraform_build
      
      - name: install terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.7"

      - name: initialise terraform working directory
        run: terraform init

      - name: check for syntax errors
        run: terraform validate
      


        
    
